[toolchain]
channel = "1.86.0"  # Updated for compatibility with diesel and latest dependencies
components = ["rustc", "cargo", "rustfmt", "clippy"]
targets = ["x86_64-unknown-linux-gnu"]
profile = "default"
